<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit819d531e65eab8fae9376f7640ad142d
{
    public static $files = array (
        'f15d016d70663d5e96ccd2b863511eb8' => __DIR__ . '/..' . '/cbschuld/browser.php/lib/Browser.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PHPSQLParser\\' => 
            array (
                0 => __DIR__ . '/..' . '/greenlion/php-sql-parser/src',
            ),
        ),
        'A' => 
        array (
            'Analog' => 
            array (
                0 => __DIR__ . '/..' . '/analog/analog/lib',
            ),
        ),
    );

    public static $classMap = array (
        'orgelmanFunctions' => __DIR__ . '/../..' . '/src/class.orgelmanFunctions.php',
        'orgelmanSQL' => __DIR__ . '/../..' . '/src/class.sql.php',
        'orgelmanText' => __DIR__ . '/../..' . '/src/class.text.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit819d531e65eab8fae9376f7640ad142d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit819d531e65eab8fae9376f7640ad142d::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit819d531e65eab8fae9376f7640ad142d::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit819d531e65eab8fae9376f7640ad142d::$classMap;

        }, null, ClassLoader::class);
    }
}
