<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'orgelmanFunctions' => $baseDir . '/src/class.orgelmanFunctions.php',
    'orgelmanSQL' => $baseDir . '/src/class.sql.php',
    'orgelmanText' => $baseDir . '/src/class.text.php',
);
